### ISSUE TITLE
[FEATURE] Support entry group as parameter

### ISSUE THREAD

**Issue by m1n0** [GoogleCloudPlatform/datacatalog-connectors-rdbms#14]
Entry group seems to be the correct level of abstraction in data catalog to distinguish different metadata sources (i.e. databases, e.g. two PG dbs should have a separate entry group each) yet connectors use hardoced entry group and delete all data from it before pushing newly crawled data into the catalog.

It seems that what we need is an entry group parameter to make ingesting multiple DBs metadata possible. We will happily provide MR for this, at least for the postgres connector, but could you please validate our thinking here?

Thanks

**Comment by mesmacosta** [comment]
Hi @m1n0,

That's one really important use case, having many multiple DBs.

In the BI connectors there was a similar use case, and the connector TAGs all entries with the server host. When running the delete logic, it only deletes the entries that are in scope of that server host.

I'm interested to see which one better fits your needs.

Anyway giving users control on what entry group name they are using is important. Please go ahead and send the MR for this, it should be a quick fix at the CLI code.

And do you think adding the host server TAG is helpful? (plus the delete logic within the host server) We were thinking about adding this feature to the RDBMS connectors but haven't received requests for it yet.
