### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Mathss** [GoogleCloudPlatform/datacatalog-connectors-rdbms#24]
**What happened**:
I had an error while installing the library from the source, or building the docker file. Below the error code:

```
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\matheus.oliveira\appdata\local\programs\python\python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Us
ers\\MATHEU~1.OLI\\AppData\\Local\\Temp\\pip-req-build-_63dnyzz\\setup.py'"'"'; __file__='"'"'C:\\Users\\MATHEU~1.OLI\\AppData\\Local\\Temp\\pip-req-build-
_63dnyzz\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code
, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\MATHEU~1.OLI\AppData\Local\Temp\pip-pip-egg-info-y02ojd5i'
         cwd: C:\Users\MATHEU~1.OLI\AppData\Local\Temp\pip-req-build-_63dnyzz\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\MATHEU~1.OLI\AppData\Local\Temp\pip-req-build-_63dnyzz\setup.py", line 22, in <module>
        readme = readme_file.read()
      File "c:\users\matheus.oliveira\appdata\local\programs\python\python37\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 288: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

**What you expected to happen**:
Build succesffully

**How to reproduce it (as minimally and precisely as possible)**:
I've just followed the tutorial in the main readme for the postgresql connector. I'm using a windows machine x64 with python 3.7

**Anything else we need to know?**:
I actually discover the reason. As stated in the error there is a problematic byte found while reading the readme file. (if we delete its content it works file). After converting the text to code I identify it is part of the ⚠️ symbol:

![image](https://user-images.githubusercontent.com/6992684/95395545-4397a500-08d5-11eb-8836-303ab153c2cb.png)

Also in a black space in the text

![image](https://user-images.githubusercontent.com/6992684/95395693-98d3b680-08d5-11eb-8d35-d8dca7450f5d.png)

I'm not sure if I was supposed to do some configuration to bypass this of if it's really a problem for windows. But anyway, I though it would be nice to report

**Comment by mesmacosta** [comment]
Thanks for filling this @Mathss.

**Comment by mesmacosta** [comment]
@Mathss could you verify if it works now?

Thanks.

**Comment by Mathss** [comment]
@mesmacosta It works fines now, thank you!
