### ISSUE TITLE
[FEATURE] Add PostgreSQL parsing query using pg_catalog instead of information_schema 

### ISSUE THREAD

**Issue by Mathss** [GoogleCloudPlatform/datacatalog-connectors-rdbms#34]
**What would you like to be added**: 

It would be nice have another query option to parse the postreSQL tables using the **pg_catalog** instead of the **information_schema**. 

I am doing a translation of the original query to a new one using pg_catalog and returning the same output fields, but it is still a work in progress. Not sure how I would enable some parameter in the code to use this query instead of the standard (or maybe use this as the main query)

```
SELECT
  t.schemaname AS schema_name,
  t.tablename AS table_name,
  'BASE TABLE' AS table_type,
  c.attname AS column_name,
  NULL AS column_default_value,
  CASE
    WHEN c.attnotnull = 'f' THEN 'YES'
    ELSE 'NO'
  END AS column_nullable,
  c.atttypid :: regtype AS column_type,
  NULL AS column_char_length,
  NULL AS column_numeric_precision,
  NULL AS column_enum_values,
  NULL AS table_size_mb
FROM
  pg_catalog.pg_tables t
  LEFT JOIN pg_attribute c ON concat('public.', t.tablename) :: regclass = c.attrelid
WHERE
  t.schemaname NOT IN ('pg_catalog', 'information_schema', 'pg_toast', 'gp_toolkit', 'pg_internal','externo','views')
  AND c.attname NOT IN ('cmax', 'xmax','cmin', 'xmin', 'ctid', 'tableoid')
  AND attnum > 0
  AND NOT attisdropped
ORDER BY
  t.tablename,
  c.attname;
```

**Why is this needed**:
Like that, we can parse the tables/columns with Postgres specific information that that doesn't go along with the rules of the SQL standard (in my case all the tables in my db were in this situation). 

Otherwise the query doesn't not parse them

**Comment by mesmacosta** [comment]
I'd suggest adding a new query to the connector [config](https://github.com/GoogleCloudPlatform/datacatalog-connectors-rdbms/tree/master/google-datacatalog-postgresql-connector/src/google/datacatalog_connectors/postgresql/config). And add an attribute to the (ingest_cfg.yaml)[https://github.com/GoogleCloudPlatform/datacatalog-connectors-rdbms/blob/master/google-datacatalog-postgresql-connector/ingest_cfg.yaml], where the user can specify which query will be executed.

WDYT?

**Comment by Mathss** [comment]
That sounds good, I will try to implement here and make the PR. Thanks for the reply

**Comment by mesmacosta** [comment]
Sounds good, look forward to it.

**Comment by mesmacosta** [comment]
@Mathss 

I've added the option to provide a different query, let me know when your query is ready to be integrated into the connector.

**Comment by Mathss** [comment]
Hello @mesmacosta, sorry for the delay. Unfortunately the query is not yet 100% adapted for the previous fields. I was having some problems to get some information, so for now I'm null for some columns. I will try work on it for the next weeks and let you know if I have any progress

For now this is the query:
```
SELECT
  t.schemaname AS schema_name,
  t.tablename AS table_name,
  'BASE TABLE' AS table_type,
  c.attname AS column_name,
  NULL AS column_default_value,
  CASE
    WHEN c.attnotnull = 'f' THEN 'YES'
    ELSE 'NO'
  END AS column_nullable,
  c.atttypid :: regtype AS column_type,
  CASE
	WHEN c.atttypid != 1043 THEN NULL
	ELSE c.atttypmod
  END AS column_char_length,
  NULL AS column_numeric_precision,
  NULL AS column_enum_values,
  pg_total_relation_size(relid)/1024 AS table_size_mb
FROM
  pg_catalog.pg_tables t
  LEFT JOIN pg_attribute c ON concat('public.', t.tablename) :: regclass = c.attrelid
  LEFT JOIN pg_catalog.pg_statio_user_tables s ON t.tablename = s.relname
WHERE
  t.schemaname NOT IN ('pg_catalog', 'information_schema', 'pg_toast', 'gp_toolkit', 'pg_internal', 'views')
  AND c.attname NOT IN ('cmax', 'xmax','cmin', 'xmin', 'ctid', 'tableoid')
  AND attnum > 0
  AND NOT attisdropped
ORDER BY
  t.tablename,
  c.attname;
```

**Comment by Mathss** [comment]
I also noticed that in my use case (where I parse all sql instance in my gcp and run the adequated adapter for it) the config file always being applied hence running the postgres specific query in the other databases

It migth be some wrong architecture I'm using, so I am still checking other ways

**Comment by mesmacosta** [comment]
Hi @Mathss 
`the config file always being applied hence running the postgres specific query in the other databases`

Are you using the [config](https://github.com/GoogleCloudPlatform/datacatalog-connectors-rdbms/tree/master/google-datacatalog-postgresql-connector/src/google/datacatalog_connectors/postgresql/config)? can you elaborate on that?
