### ISSUE TITLE
[BUG] INSERT permissions required for mysql connector

### ISSUE THREAD

**Issue by dwilliams782** [GoogleCloudPlatform/datacatalog-connectors-rdbms#50]
**What happened**:

When running the mysql connector, it fails with a read only user:

```
mysql.connector.errors.ProgrammingError: 1142 (42000): INSERT command denied to user 'read-only'@'10.31.9.31' for table 'Agent'
```

**What you expected to happen**:

This should be able to run as a read only user.

**How to reproduce it (as minimally and precisely as possible)**:

Create a new read only user and execute the connector.

**Anything else we need to know?**:
I'm not sure if this is a bug exactly as it may be by design, but I had a look at the query in `metadata_query.sql` and I can't see why it would be trying to do an insert. Is the required user permissions documented anywhere? Or can anyone help advise on what I would need to set up?

**Comment by mesmacosta** [comment]
Thanks for opening this @dwilliams782,

You need `READ` permission in the following  `information_schema` tables: `information_schema.tables` and `information_schema.columns`.

Can you test the `metadata_query.sql` using the user you created with the mysql CLI, and see if you have the correct access?

We will improve the documentation with the required database permissions.

**Comment by dwilliams782** [comment]
Thanks for the quick response (again!)

![image](https://user-images.githubusercontent.com/42545485/99682093-c8e6ab80-2a76-11eb-8497-6ce0d890647f.png)

I am logged in as a new user 'read-only' I created with the following command:

`grant select on database_name.* to 'read-only_user_name'@'%' identified by 'password';`

The query works for the user but does not work via the connector:

```
mysql.connector.errors.ProgrammingError: 1142 (42000): INSERT command denied to user 'read-only'@'10.31.4.156' for table 'Agent'
```

This is just running mysql in a container (`registry.hub.docker.com/karhoo/mysql:5.7`) and we've seen the same result connecting a read-only user to a GCP mysql instance.

**Comment by mesmacosta** [comment]
Also can you test the `ANALYZE TABLE [MY_TABLE]` statement?

**Comment by dwilliams782** [comment]
```
mysql> ANALYZE TABLE Agent;
ERROR 1142 (42000): INSERT command denied to user 'read-only'@'localhost' for table 'Agent'
```

**Comment by mesmacosta** [comment]
If you don't want to have that behavior, you can turn off the `refresh_metadata_tables` flag in the `ingest_cfg.yaml` file, for example:

```
# Using this configuration file, you can turn on or off the scraping of optional pieces of data.

# Runs ANALYZE command for each user table, to update metadata tables and make database statistics more accurate.
# Note, that it might take long time to ANALYZE big tables
refresh_metadata_tables: false

# Retrieve number of rows in each table
sync_row_counts: true
```

We will update the docs, with the required permissions if you have the  flag ON. Can you test with it disabled?

**Comment by dwilliams782** [comment]
Thanks, I've confirmed this works OK with a read only user without the ANALYZE command enabled. This will do for my testing. Appreciate the help!
