### ISSUE TITLE
[BUG] Update rdbms2datacatalog lib.

### ISSUE THREAD

**Issue by mesmacosta** [GoogleCloudPlatform/datacatalog-connectors-rdbms#6]
**What happened**:
Changes to the commons **rdbms** library have been merged #5, we need to update the libs folder.

**What you expected to happen**:
Update the **libs** folder.

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:
This is done by scripting while we don't have the packages in pypi.

**Comment by m1n0** [comment]
Should we push to pypi? It would be useful for dev as well, especially when running stuff in docker - we would then be able to put together both dev and prod-ish images without so much hassle

**Comment by mesmacosta** [comment]
Yes, I've opened a feature request for it:
https://github.com/GoogleCloudPlatform/datacatalog-connectors-rdbms/issues/9
