### ISSUE TITLE
[FEATURE] Add unix-socket parameter for MySQL connector

### ISSUE THREAD

**Issue by Mathss** [GoogleCloudPlatform/datacatalog-connectors-rdbms#60]
**What would you like to be added**: 
Below my current workaround. The names migth not be the best:
- New unix_socket parameter to be parsed 
![image](https://user-images.githubusercontent.com/6992684/101546227-43745e00-3987-11eb-90ec-bf4a0cb104da.png)
-  Use of the new parameter in socket connections
![image](https://user-images.githubusercontent.com/6992684/101546288-5424d400-3987-11eb-8a9c-67580db3d8a3.png)

**Why is this needed**: If we want to run the connector on GCP services (like app engine getting data from cloud sql) we need to use unix-socket instead of tcp. For the mysql connector it seems this can only be done by specifying another parameter **unix_socket** instead of the **host**.

**Comment by mesmacosta** [comment]
Hi @Mathss, 

Thanks for opening this.

can you add the documentation from google app engine or the Python mysql client, of the **unix-socket** parameter mentioned in your PR?

So we can discuss the proper naming and if it makes sense to create a new parameter.

**Comment by Mathss** [comment]
Sure!

https://dev.mysql.com/doc/connector-python/en/connector-python-connectargs.html

![image](https://user-images.githubusercontent.com/6992684/101631057-845d8880-3a02-11eb-8347-21c93b7bf382.png)


In AppEngine documentation example it uses SQL Alchemy on top of the mysql connector so it's a little bit different:

![image](https://user-images.githubusercontent.com/6992684/101631391-03eb5780-3a03-11eb-97c0-95786ff7960b.png)

https://cloud.google.com/sql/docs/mysql/connect-app-engine-standard

**Comment by mesmacosta** [comment]
looks good, thanks for the detailed info!
