### ISSUE TITLE
[BUG] New columns not being ingested

### ISSUE THREAD

**Issue by vishinde** [GoogleCloudPlatform/datacatalog-connectors-rdbms#62]
**What happened**:
When new columns are added in MySQL, they are not being ingested by the connector when already run on that RDBMS

**What you expected to happen**:
New columns get added in data catalog on re-running connector

**How to reproduce it (as minimally and precisely as possible)**:
Run connector for MySQL database
Add columns to one of the table in the database
Re-run the connector. The new column wont be added

**Anything else we need to know?**:

**Comment by mesmacosta** [comment]
Thanks @vishinde for filling this.
