### ISSUE TITLE
[BUG] Redshift connector query misses late-binding views

### ISSUE THREAD

**Issue by ealtuna** [GoogleCloudPlatform/datacatalog-connectors-rdbms#83]
**What happened**:

When running the connector with a Redshift database, [late-binding views](https://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_VIEW.html#r_CREATE_VIEW_late-binding-views) are not included.

**What you expected to happen**:
Late-binding views should be included.

**How to reproduce it (as minimally and precisely as possible)**:
Create a late-binding view using the syntax:

`create view event_vw as select * from public.event with no schema binding;
`

Run the connector and note the view is not included in Google Data Catalog.

**Anything else we need to know?**:

The table [SVV_COLUMNS](https://docs.aws.amazon.com/redshift/latest/dg/r_SVV_COLUMNS.html) can be used instead of `information_schema.columns` to view catalog information about the columns of local and external tables and views, including late-binding views.

However, I am not sure if this table exists in all the supported versions of Redshift.

**Comment by mesmacosta** [comment]
Thanks for opening this @ealtuna.

Do you want to take a stab on creating the code for this? 
I'd suggest you to use the [SQL Objects](https://github.com/GoogleCloudPlatform/datacatalog-connectors-rdbms/tree/master/google-datacatalog-rdbms-connector#42-add-support-for-sql-objects) mechanism:
![Screen Shot 2022-01-15 at 14 46 03](https://user-images.githubusercontent.com/3176836/149632191-8b71f29f-605c-43a5-9365-103ddc2040f1.png)

So the basic idea, is to create a new type for the redshift connector as `late_binding_view`, if you create the proper files as explained in the documentation, the SQL will be ingested as separate entities in Data Catalog. Then please document the version you used to test this, and users can disable the config if their own versions don't support it, WDYT?
