### ISSUE TITLE
[FEATURE] Publish connectors to pypi.

### ISSUE THREAD

**Issue by mesmacosta** [GoogleCloudPlatform/datacatalog-connectors-rdbms#9]
**What would you like to be added**:
Currently we store the package dependencies in the lib folder, ideally we should have all dependencies in pypi.

**Why is this needed**:
Makes the environment set up easier, only need to do a single command to install each connector, this improves the dev experience and is less error prone.

**Comment by m1n0** [comment]
Do you plan on doing some changes before publishing? Can I help?

**Comment by mesmacosta** [comment]
The way the packages are structure, they should comply with pypi. Changes in my mind, are update the `setup.py` with the dependencies once they are in pypi, and remove the lib folder. I will let you know, if anything else is required.

**Comment by m1n0** [comment]
Hi, any update on this pls? It seems like the packages could be uploaded as they are

**Comment by mesmacosta** [comment]
Hi @m1n0,
We are checking the right PyPI user to publish all the datacatalog connectors and their dependencies.

**Comment by mesmacosta** [comment]
@m1n0 we have an earlier working version on the branch:
https://github.com/GoogleCloudPlatform/datacatalog-connectors-rdbms/tree/release-v0.5.0

This is the PostgreSQL package: https://pypi.org/project/google-datacatalog-postgresql-connector/

We changed the package names to comply with other google open source projects on PyPI.

I'm still reviewing the latest changes, but if you can give feedback if it works well for you, would be really helpful.

Thanks.
